# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateField(verbose_name='time of award')),
            ],
        ),
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eduation', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('basic_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.BasicInformation')),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AddField(
            model_name='award',
            name='basic_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.BasicInformation'),
        ),
    ]
