# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20170307_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='school',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
