# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_basicinformation_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='school',
            field=models.CharField(max_length=50),
        ),
    ]
