# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20170308_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinformation',
            old_name='eduation',
            new_name='education',
        ),
    ]
